name: React CI CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
        node-version: [18.x]
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ONE_HOST }}
        username: ${{ secrets.ONE_USER }}
        key: ${{ secrets.ONE_KEY }}
        port: ${{ secrets.ONE_PORT }}
        script: |
          cd /var/www/onelocal/event-admin-react/ONE-react
          pwd
          git pull origin main
          git status
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          node -v
          npm -v
          npm install
          npm list
          npm run build
